import React from 'react';

import Link from 'next/link';

export default function Content() {
  // --- SEO DATA REFERENCE ---
  // SEO TITLE: Power Converter Online | Watts to HP Calculator
  // META DESCRIPTION: Free online power converter tool. Easily convert between Watts, Kilowatts (kW), Megawatts, Horsepower (HP), BTU, and more. Perfect for appliances and auto engines.
  // URL SLUG: /calculator/conversion/power
  // PRIMARY KEYWORD: power converter
  // SECONDARY KEYWORDS: watts to hp converter, kw to hp calculator, horsepower to watts, megawatt to kilowatt, btu to watts calculator, metric horsepower, power conversion tool
  // LONG-TAIL KEYWORDS: how to convert kilowatts to horsepower, 1 hp motor in watts calculation, convert car engine hp to kw, difference between metric and imperial horsepower

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "How many Watts are in one Horsepower (HP)?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "One Imperial (Mechanical) Horsepower is exactly equal to 745.7 Watts. However, if you are using Metric Horsepower (PS/cv), one metric HP equals 735.5 Watts."
        }
      },
      {
        "@type": "Question",
        name: "What is the difference between kW and kVA?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Kilowatts (kW) represent real power—the actual power consumed by an appliance to do work. Kilovolt-Amperes (kVA) represent apparent power, which is the total power supplied by the grid. For highly efficient appliances, kW and kVA are nearly identical, but in industrial motors, kVA is usually higher."
        }
      },
      {
        "@type": "Question",
        name: "Why is air conditioning cooling measured in BTU or Tons instead of Watts?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "BTU (British Thermal Unit) measures heat extraction over time (BTU/hour). While you can measure an AC's cooling power in Watts, the HVAC industry historically standardized on BTU and Refrigeration Tons. One Ton of cooling is equal to 12,000 BTU/hr, which converts to roughly 3,516 Watts of thermal power."
        }
      },
      {
        "@type": "Question",
        name: "What is the difference between Imperial and Metric Horsepower?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Imperial Horsepower (used in the US, UK, and often India) defines the power needed to lift 550 pounds by one foot in one second (745.7 W). Metric Horsepower (PS), used widely in Europe and Japan, defines the power to lift 75 kilograms by one meter in one second (735.5 W)."
        }
      },
      {
        "@type": "Question",
        name: "How do I calculate my home inverter capacity?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "First, sum up the wattage of all the appliances you want to run simultaneously (e.g., 3 fans at 70W each + 2 lights at 10W each = 230W). Divide this total wattage by the power factor (usually 0.8) to get the required VA (Volt-Ampere) rating. So, 230W / 0.8 = 287.5 VA. You should buy an inverter with at least a 300 VA capacity."
        }
      }
    ]
  };

  return (
    <div className="space-y-10 max-w-4xl mx-auto text-gray-800 leading-relaxed mt-8">
      {/* --- SEO TAGS --- */}
      

      {/* INTRODUCTION */}
      <section>
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-5">
          Power Converter
        </h1>
        <p className="mb-4">
          In the world of physics, <strong>power</strong> is defined as the rate at which work is done or energy is transferred over time. Whether you are measuring the electricity consumed by a household LED lightbulb, the mechanical force generated by a car engine, or the cooling capacity of your living room air conditioner, you are measuring power.
        </p>
        <p className="mb-4">
          Because power is measured across drastically different industries globally, we have inherited several different units of measurement. Electricians and physicists rely heavily on the metric system's <strong>Watts (W)</strong> and <strong>Kilowatts (kW)</strong>, while the automotive, agricultural, and heavy machinery industries in India still heavily rely on <strong>Horsepower (HP)</strong>. Furthermore, the HVAC (heating and cooling) industry often uses thermal measurements like <strong>BTUs per hour</strong>.
        </p>
        <p>
          Our free, precision <strong>Power Converter</strong> tool eliminates the confusion of complex manual calculations. Whether you are comparing car engine specifications, buying a new home water pump, or calculating the power draw of industrial equipment, this calculator handles over a dozen global power units instantly.
        </p>
      </section>

      {/* HOW TO USE */}
      <section className="bg-blue-50 p-6 rounded-xl border border-blue-100">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">How to Use the Power Converter</h2>
        <p className="mb-4 text-gray-700">
          This calculator lets you instantly convert a power value from one unit of measurement to another. Here is a step-by-step guide to using the tool:
        </p>
        <ol className="list-decimal pl-6 space-y-3 text-gray-800 mb-6">
          <li><strong>Enter the Value:</strong> Type the specific numerical value of the power you wish to convert in the "Value" box.</li>
          <li><strong>Select 'From Unit':</strong> Choose the unit you are starting with from the first dropdown menu.</li>
          <li><strong>Select 'To Unit':</strong> Choose the unit you want to convert the value into from the second dropdown menu. The conversion will display instantly.</li>
        </ol>

        <h3 className="font-semibold text-blue-900 mb-2 mt-4 text-lg">Supported Power Units</h3>
        <p className="mb-3 text-sm text-gray-700">We categorize our supported units into three main groups: Electrical, Mechanical, and Thermal/Work rate.</p>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
          <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100">
            <h4 className="font-bold text-gray-900 mb-2 border-b pb-1">Electrical (SI Units)</h4>
            <ul className="list-disc pl-5 space-y-1 text-gray-700">
              <li>Watts (W)</li>
              <li>Kilowatts (kW)</li>
              <li>Megawatts (MW)</li>
            </ul>
          </div>
          <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-100">
            <h4 className="font-bold text-gray-900 mb-2 border-b pb-1">Mechanical Units</h4>
            <ul className="list-disc pl-5 space-y-1 text-gray-700">
              <li>Imperial Horsepower (hp)</li>
              <li>Metric Horsepower (PS/cv)</li>
            </ul>
          </div>
        </div>
      </section>

      {/* FORMULA SECTION */}
      <section>
        <h2 className="text-2xl font-bold mb-4 text-gray-900">Understanding Power Conversions & Formulas</h2>
        <p className="mb-6 text-gray-700">
          The <strong>Watt (W)</strong> is the fundamental unit of power in the International System of Units (SI). One Watt is defined mathematically as one Joule of energy transferred per second (1 W = 1 J/s). Because a single Watt is a very small amount of power, it is usually scaled up for household appliances (Kilowatts) and national power grids (Megawatts and Gigawatts).
        </p>

        <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 mt-6">
          <h3 className="text-xl font-bold text-gray-900 mb-4">Electrical Power: Watts and Kilowatts</h3>
          <div className="bg-white p-4 rounded shadow-sm border-l-4 border-amber-500">
            <ul className="text-sm space-y-3 text-gray-700">
              <li><strong>Kilowatts to Watts:</strong> Multiply kW by 1,000. <br/><span className="text-gray-500 italic">(Example: A 1.5 kW electric kettle uses 1,500 Watts)</span></li>
              <li><strong>Megawatts to Kilowatts:</strong> Multiply MW by 1,000. <br/><span className="text-gray-500 italic">(Example: A 2 MW wind turbine generates 2,000 kW)</span></li>
              <li><strong>Watts to Kilowatts:</strong> Divide W by 1,000. <br/><span className="text-gray-500 italic">(Example: A 60 W ceiling fan consumes 0.06 kW)</span></li>
            </ul>
          </div>
        </div>

        <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 mt-6">
          <h3 className="text-xl font-bold text-gray-900 mb-4">Mechanical Power: Horsepower (hp)</h3>
          <p className="text-sm mb-4">
            The term "horsepower" was famously coined by engineer James Watt in the 18th century to compare the output of his newly invented steam engines with the physical pulling power of draft horses. Today, we have two different definitions of horsepower depending on your region:
          </p>
          
          <div className="space-y-4">
            <div className="bg-white p-4 rounded shadow-sm border-l-4 border-emerald-500">
              <h4 className="font-bold text-gray-900 mb-1">Imperial / Mechanical Horsepower (hp)</h4>
              <p className="text-sm text-gray-600 mb-2">Used heavily in the United States, UK, and traditionally in India for water pumps and older machinery. <strong>1 hp = 745.7 Watts.</strong></p>
              <ul className="text-sm space-y-2 text-gray-700 bg-gray-50 p-3 rounded">
                <li><strong>hp to Watts:</strong> Multiply hp by 745.7</li>
                <li><strong>hp to Kilowatts:</strong> Multiply hp by 0.7457.</li>
                <li><strong>Kilowatts to hp:</strong> Multiply kW by 1.341.</li>
              </ul>
            </div>

            <div className="bg-white p-4 rounded shadow-sm border-l-4 border-emerald-500">
              <h4 className="font-bold text-gray-900 mb-1">Metric Horsepower (PS or cv)</h4>
              <p className="text-sm text-gray-600 mb-2">Used widely by modern European and Asian car manufacturers. Written as PS (Pferdestärke) or cv (cheval-vapeur). <strong>1 PS = 735.5 Watts.</strong></p>
              <ul className="text-sm space-y-2 text-gray-700 bg-gray-50 p-3 rounded">
                <li><strong>PS to Watts:</strong> Multiply PS by 735.5</li>
                <li><strong>Kilowatts to PS:</strong> Multiply kW by 1.360.</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* WORKED EXAMPLES */}
      <section className="mt-10">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">Practical Math Examples in Daily Life</h2>
        
        <div className="space-y-6">
          {/* Example 1 */}
          <div className="border border-gray-200 rounded-lg overflow-hidden shadow-sm">
            <div className="bg-gray-50 px-5 py-3 border-b border-gray-200">
              <h3 className="font-bold text-gray-900">Example 1: Buying a Home Water Pump</h3>
            </div>
            <div className="p-5 bg-white text-gray-800 text-sm leading-relaxed">
              <p className="mb-3"><strong>Scenario:</strong> You are buying a residential water pump in India. The shopkeeper tells you it has a <strong>1.5 HP (Imperial)</strong> motor. You want to know how many Watts it consumes to check if your home inverter can support it.</p>
              <ul className="list-disc pl-5 mb-3 text-gray-700 space-y-1">
                <li><strong>Identify the formula:</strong> 1 Imperial hp = 745.7 Watts.</li>
                <li><strong>Set up the calculation:</strong> Multiply the motor horsepower by the Watt conversion factor.</li>
                <li><strong>Calculate:</strong> 1.5 x 745.7 = 1,118.55 Watts.</li>
              </ul>
              <p className="text-blue-700 font-semibold">Conclusion: The 1.5 HP water pump will draw approximately 1,118 Watts (or 1.1 kW) of electricity.</p>
            </div>
          </div>

          {/* Example 2 */}
          <div className="border border-gray-200 rounded-lg overflow-hidden shadow-sm">
            <div className="bg-gray-50 px-5 py-3 border-b border-gray-200">
              <h3 className="font-bold text-gray-900">Example 2: Understanding Car Engine Specifications</h3>
            </div>
            <div className="p-5 bg-white text-gray-800 text-sm leading-relaxed">
              <p className="mb-3"><strong>Scenario:</strong> You are comparing two cars. Car A generates <strong>120 PS (Metric Horsepower)</strong>. Car B's brochure says it generates <strong>85 Kilowatts (kW)</strong>. You need to convert Car B's power into PS to make a fair comparison.</p>
              <ul className="list-disc pl-5 mb-3 text-gray-700 space-y-2">
                <li><strong>Identify the formula:</strong> To convert kW to Metric HP (PS), multiply the kW by 1.360.</li>
                <li><strong>Calculate:</strong> 85 kW x 1.360 = 115.6 PS.</li>
              </ul>
              <p className="text-emerald-700 font-semibold">Conclusion: Car B generates 115.6 PS. Therefore, Car A (120 PS) has a slightly more powerful engine than Car B.</p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ SECTION */}
      <section className="mt-10">
        <h2 className="text-2xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {faqSchema.mainEntity.map((faq, index) => (
            <details key={index} className="group border border-gray-200 rounded-lg bg-white open:shadow-md transition-all duration-200">
              <summary className="font-semibold px-5 py-4 cursor-pointer text-gray-900 list-none flex justify-between items-center">
                {faq.name}
                <span className="text-blue-600 group-open:rotate-180 transition-transform">▼</span>
              </summary>
              <div className="px-5 pb-5 text-gray-600 text-sm leading-relaxed border-t border-gray-100 pt-3">
                {faq.acceptedAnswer.text}
              </div>
            </details>
          ))}
        </div>
      </section>

      {/* INTERNAL LINKING */}
      <section className="bg-gray-50 p-6 rounded-xl border border-gray-200 mt-10">
        <h3 className="font-bold text-xl mb-4 text-gray-900">Explore More Scientific & Everyday Calculators</h3>
        <p className="text-sm mb-5 text-gray-600">
          Make complex daily measurements effortless with our comprehensive suite of conversion tools:
        </p>
        <div className="flex flex-wrap gap-3">
          <Link href="/calculator/conversion/energy" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Energy Converter</Link>
          <Link href="/calculator/conversion/pressure" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Pressure Converter</Link>
          <Link href="/calculator/conversion/torque" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Torque Converter</Link>
          <Link href="/calculator/conversion/speed" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Speed Converter</Link>
          <Link href="/calculator/conversion/temperature" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Temperature Converter</Link>
          <Link href="/calculator/conversion/weight" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Weight Converter</Link>
          <Link href="/calculator/conversion/volume" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Volume Converter</Link>
          <Link href="/calculator/conversion/area" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Area Converter</Link>
          <Link href="/calculator/conversion/angle" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Angle Converter</Link>
          <Link href="/calculator/conversion/time" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Time Converter</Link>
          <Link href="/calculator/conversion/unit" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Universal Unit Converter</Link>
          <Link href="/calculator/conversion/fraction-decimal" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Fraction & Decimal</Link>
          <Link href="/calculator/conversion/number-base" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Number Base Converter</Link>
          <Link href="/calculator/conversion/roman" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Roman Numerals</Link>
          <Link href="/calculator/conversion/cooking" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Cooking Calculator</Link>
          <Link href="/calculator/conversion/data-transfer" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Data Transfer Rate</Link>
          <Link href="/calculator/conversion/digital-storage" className="text-sm text-blue-700 font-medium hover:underline bg-white px-4 py-2 rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-blue-50">Digital Storage</Link>
        </div>
      </section>
    </div>
  );
}