import React from 'react';

export default function Content() {
  return (
    <div className="space-y-8 max-w-4xl mx-auto text-gray-700">
      <section>
        <h2 className="text-2xl font-bold mb-4 text-gray-900">Understanding Power Conversions</h2>
        <p className="mb-4">
          In physics, <strong>power</strong> is the rate at which work is done or energy is transferred over time. Whether you are measuring the electricity consumed by a lightbulb or the mechanical force generated by a car engine, you are measuring power!
        </p>
        <p className="mb-4">
          Because power is measured in different industries, we end up with different units. Electricians and physicists rely on <strong>Watts</strong> (the metric standard), while the automotive and heavy machinery industries still heavily rely on <strong>Horsepower</strong>.
        </p>
        
      </section>

      <section className="bg-calc-beige/30 p-6 rounded-xl border border-calc-lightGray mt-8">
        <h3 className="text-xl font-bold text-gray-900 mb-4">Electrical Power: Watts and Kilowatts</h3>
        <p className="text-sm mb-4">
          The <strong>Watt (W)</strong> is the fundamental unit of power in the International System of Units (SI). One Watt is defined as one Joule of energy transferred per second (1 W = 1 J/s). Because a single Watt is a very small amount of power, it is usually scaled up for household and industrial use.
        </p>
        <div className="bg-white p-4 rounded shadow-sm border-l-4 border-blue-500 mb-4">
          <h4 className="font-bold text-gray-900 mb-1">Watt Conversion Formulas</h4>
          <ul className="text-sm space-y-2 text-gray-700 mt-2">
            <li><strong>Kilowatts to Watts:</strong> Multiply by 1,000. <em>(Example: A 1.5 kW microwave uses 1,500 Watts)</em></li>
            <li><strong>Megawatts to Kilowatts:</strong> Multiply by 1,000. <em>(Example: A 2 MW wind turbine generates 2,000 kW)</em></li>
            <li><strong>Watts to Kilowatts:</strong> Divide by 1,000. <em>(Example: A 60 W lightbulb consumes 0.06 kW)</em></li>
          </ul>
        </div>
      </section>

      <section className="bg-calc-beige/30 p-6 rounded-xl border border-calc-lightGray mt-8">
        <h3 className="text-xl font-bold text-gray-900 mb-4">Mechanical Power: Horsepower (hp)</h3>
        <p className="text-sm mb-4">
          The term "horsepower" was famously coined by engineer James Watt in the 18th century to compare the output of his newly invented steam engines with the power of draft horses. Today, we have two slightly different definitions of horsepower depending on where you live:
        </p>
        
        
        <div className="space-y-4">
          <div className="bg-white p-4 rounded shadow-sm border-l-4 border-calc-green">
            <h4 className="font-bold text-gray-900 mb-1">Imperial / Mechanical Horsepower (hp)</h4>
            <p className="text-sm text-gray-600 mb-2">Used primarily in the United States and the UK. It is defined as exactly <strong>745.7 Watts</strong>.</p>
            <ul className="text-sm space-y-2 text-gray-700">
              <li><strong>hp to Watts:</strong> Multiply hp by 745.7</li>
              <li><strong>hp to Kilowatts:</strong> Multiply hp by 0.7457. <em>(Example: A 400 hp car engine produces about 298 kW of power)</em></li>
              <li><strong>Kilowatts to hp:</strong> Multiply kW by 1.341.</li>
            </ul>
          </div>

          <div className="bg-white p-4 rounded shadow-sm border-l-4 border-calc-green">
            <h4 className="font-bold text-gray-900 mb-1">Metric Horsepower (PS or cv)</h4>
            <p className="text-sm text-gray-600 mb-2">Used primarily in Europe and Asia. It is defined as exactly <strong>735.5 Watts</strong>. It is often written as PS (Pferdestärke in German) or cv (cheval-vapeur in French).</p>
            <ul className="text-sm space-y-2 text-gray-700">
              <li><strong>PS to Watts:</strong> Multiply PS by 735.5</li>
              <li><strong>Kilowatts to PS:</strong> Multiply kW by 1.360. <em>(Example: A 100 kW electric motor produces about 136 PS)</em></li>
            </ul>
          </div>
        </div>
      </section>
    </div>
  );
}